package wangdaye.com.geometricweather.theme.compose.night
import androidx.compose.ui.graphics.Color

val night_md_theme_dark_primary = Color(0xFF50d7ec)
val night_md_theme_dark_onPrimary = Color(0xFF00363e)
val night_md_theme_dark_primaryContainer = Color(0xFF004f59)
val night_md_theme_dark_onPrimaryContainer = Color(0xFF95f0ff)
val night_md_theme_dark_secondary = Color(0xFFb8c4ff)
val night_md_theme_dark_onSecondary = Color(0xFF132879)
val night_md_theme_dark_secondaryContainer = Color(0xFF2d4090)
val night_md_theme_dark_onSecondaryContainer = Color(0xFFdde1ff)
val night_md_theme_dark_tertiary = Color(0xFFedc148)
val night_md_theme_dark_onTertiary = Color(0xFF3f2e00)
val night_md_theme_dark_tertiaryContainer = Color(0xFF5a4400)
val night_md_theme_dark_onTertiaryContainer = Color(0xFFffdf8c)
val night_md_theme_dark_error = Color(0xFFF2B8B5)
val night_md_theme_dark_errorContainer = Color(0xFF8C1D18)
val night_md_theme_dark_onError = Color(0xFF601410)
val night_md_theme_dark_onErrorContainer = Color(0xFFF9DEDC)
val night_md_theme_dark_background = Color(0xFF1b1b1d)
val night_md_theme_dark_onBackground = Color(0xFFe3e2e6)
val night_md_theme_dark_surface = Color(0xFF1b1b1d)
val night_md_theme_dark_onSurface = Color(0xFFe3e2e6)
val night_md_theme_dark_surfaceVariant = Color(0xFF49454F)
val night_md_theme_dark_onSurfaceVariant = Color(0xFFCAC4D0)
val night_md_theme_dark_outline = Color(0x10ffffff)
val night_md_theme_dark_inverseOnSurface = Color(0xFF1b1b1d)
val night_md_theme_dark_inverseSurface = Color(0xFFe3e2e6)
val night_md_theme_dark_inversePrimary = Color(0xFF006875)
val night_md_theme_dark_shadow = Color(0xFF000000)

val night_seed = Color(0xFF6750A4)
val night_error = Color(0xFFB3261E)