package wangdaye.com.geometricweather.theme.compose.night
import androidx.compose.ui.graphics.Color

val night_md_theme_dark_primary = Color(0xFFbac3ff)
val night_md_theme_dark_onPrimary = Color(0xFF182778)
val night_md_theme_dark_primaryContainer = Color(0xFF313f90)
val night_md_theme_dark_onPrimaryContainer = Color(0xFFdde0ff)
val night_md_theme_dark_secondary = Color(0xFF50d7ec)
val night_md_theme_dark_onSecondary = Color(0xFF00363e)
val night_md_theme_dark_secondaryContainer = Color(0xFF004f59)
val night_md_theme_dark_onSecondaryContainer = Color(0xFF95f0ff)
val night_md_theme_dark_tertiary = Color(0xFFf0c048)
val night_md_theme_dark_onTertiary = Color(0xFF3f2e00)
val night_md_theme_dark_tertiaryContainer = Color(0xFF5b4300)
val night_md_theme_dark_onTertiaryContainer = Color(0xFFffdf95)
val night_md_theme_dark_error = Color(0xFFF2B8B5)
val night_md_theme_dark_errorContainer = Color(0xFF8C1D18)
val night_md_theme_dark_onError = Color(0xFF601410)
val night_md_theme_dark_onErrorContainer = Color(0xFFF9DEDC)
val night_md_theme_dark_background = Color(0xFF1b1b1b)
val night_md_theme_dark_onBackground = Color(0xFFe2e2e6)
val night_md_theme_dark_surface = Color(0xFF1b1b1b)
val night_md_theme_dark_onSurface = Color(0xFFe2e2e6)
val night_md_theme_dark_surfaceVariant = Color(0xFF49454F)
val night_md_theme_dark_onSurfaceVariant = Color(0xFFCAC4D0)
val night_md_theme_dark_outline = Color(0xff363636)
val night_md_theme_dark_inverseOnSurface = Color(0xFF1b1b1b)
val night_md_theme_dark_inverseSurface = Color(0xFFe2e2e6)
val night_md_theme_dark_inversePrimary = Color(0xFF4a57a9)
val night_md_theme_dark_shadow = Color(0xFF000000)

val night_seed = Color(0xFF6750A4)
val night_error = Color(0xFFB3261E)