labels: Idea, Needs review
body:
  - type: textarea
    id: feature-description
    attributes:
      label: Describe your idea
      description: How can Breezy Weather be improved for the community? Suggest only one idea at a time (open a new issue for a different idea).
      placeholder: |
        Example:
          "Here is how it should work: …"
    validations:
      required: true

  - type: textarea
    id: other-details
    attributes:
      label: Other details
      placeholder: |
        Additional details and attachments.

  - type: checkboxes
    id: acknowledgements
    attributes:
      label: Acknowledgements
      description: Your issue will be closed if you don’t read this carefully.
      options:
        - label: I have searched the [existing issues](https://github.com/breezy-weather/breezy-weather/issues) and [existing discussions](https://github.com/breezy-weather/breezy-weather/discussions/categories/ideas) and this is a new ticket, **NOT** a duplicate or related to another open OR closed issue or discussion.
          required: true
        - label: The idea I’m suggesting is not in the [list of features that will not be implemented](https://github.com/breezy-weather/breezy-weather/blob/main/README.md#features-that-will-not-be-implemented).
          required: true
        - label: I have updated the app to **[version 5.4.8 or later](https://github.com/breezy-weather/breezy-weather/releases)**. Even if I’m getting updates from F-Droid default repo, I don’t need to uninstall/reinstall to update.
          required: true
        - label: I wrote my request in English, and any screenshot I attached are also in English (language can be changed from Settings > Appearance). I can write in my native language under the English text, if necessary.
          required: true
        - label: I understand that this app is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY, so I may not get a positive reply to my request, if any at all.
          required: true
