name: Idea
description: Suggest something to improve app
labels: Idea, Needs review
body:
  - type: textarea
    id: feature-description
    attributes:
      label: Describe your idea
      description: How can Breezy Weather be improved for the community? Suggest only one idea at a time (open a new issue for a different idea).
      placeholder: |
        Example:
          "Here is how it should work: …"
    validations:
      required: true

  - type: textarea
    id: other-details
    attributes:
      label: Other details
      placeholder: |
        Additional details and attachments.

  - type: checkboxes
    id: acknowledgements
    attributes:
      label: Acknowledgements
      description: Your issue will be closed if you don’t read this carefully.
      options:
        - label: I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
          required: true
        - label: I have written a short but informative title.
          required: true
        - label: My idea is not related to an existing feature described in the [Homepage](https://github.com/breezy-weather/breezy-weather/blob/main/docs/HOMEPAGE.md) document.
          required: true
        - label: I have updated the app to **[version 4.6.3 or later](https://github.com/breezy-weather/breezy-weather/releases/latest)**.
          required: true