package wangdaye.com.geometricweather.theme.compose.day
import androidx.compose.ui.graphics.Color

val day_md_theme_light_primary = Color(0xFF006875)
val day_md_theme_light_onPrimary = Color(0xFFffffff)
val day_md_theme_light_primaryContainer = Color(0xFF95f0ff)
val day_md_theme_light_onPrimaryContainer = Color(0xFF001f24)
val day_md_theme_light_secondary = Color(0xFF4658a9)
val day_md_theme_light_onSecondary = Color(0xFFffffff)
val day_md_theme_light_secondaryContainer = Color(0xFFdde1ff)
val day_md_theme_light_onSecondaryContainer = Color(0xFF00115a)
val day_md_theme_light_tertiary = Color(0xFF765a00)
val day_md_theme_light_onTertiary = Color(0xFFffffff)
val day_md_theme_light_tertiaryContainer = Color(0xFFffdf8c)
val day_md_theme_light_onTertiaryContainer = Color(0xFF251a00)
val day_md_theme_light_error = Color(0xFFB3261E)
val day_md_theme_light_errorContainer = Color(0xFFF9DEDC)
val day_md_theme_light_onError = Color(0xFFFFFFFF)
val day_md_theme_light_onErrorContainer = Color(0xFF410E0B)
val day_md_theme_light_background = Color(0xFFfdfbff)
val day_md_theme_light_onBackground = Color(0xFF1b1b1d)
val day_md_theme_light_surface = Color(0xFFfdfbff)
val day_md_theme_light_onSurface = Color(0xFF1b1b1d)
val day_md_theme_light_surfaceVariant = Color(0xFFE7E0EC)
val day_md_theme_light_onSurfaceVariant = Color(0xFF49454F)
val day_md_theme_light_outline = Color(0x10000000)
val day_md_theme_light_inverseOnSurface = Color(0xFFf2f0f4)
val day_md_theme_light_inverseSurface = Color(0xFF2f3033)
val day_md_theme_light_inversePrimary = Color(0xFF50d7ec)
val day_md_theme_light_shadow = Color(0xFF000000)

val day_seed = Color(0xFF6750A4)
val day_error = Color(0xFFB3261E)