package wangdaye.com.geometricweather.theme.compose.day
import androidx.compose.ui.graphics.Color

val day_md_theme_light_primary = Color(0xFF00677E)
val day_md_theme_light_onPrimary = Color(0xFFffffff)
val day_md_theme_light_primaryContainer = Color(0xFFB1EBFF)
val day_md_theme_light_onPrimaryContainer = Color(0xFF001F28)
val day_md_theme_light_secondary = Color(0xFF3C5BA9)
val day_md_theme_light_onSecondary = Color(0xFFffffff)
val day_md_theme_light_secondaryContainer = Color(0xFFDAE2FF)
val day_md_theme_light_onSecondaryContainer = Color(0xFF00174B)
val day_md_theme_light_tertiary = Color(0xFF785A00)
val day_md_theme_light_onTertiary = Color(0xFFffffff)
val day_md_theme_light_tertiaryContainer = Color(0xFFffdf93)
val day_md_theme_light_onTertiaryContainer = Color(0xFF261a00)
val day_md_theme_light_error = Color(0xFFB3261E)
val day_md_theme_light_errorContainer = Color(0xFFF9DEDC)
val day_md_theme_light_onError = Color(0xFFFFFFFF)
val day_md_theme_light_onErrorContainer = Color(0xFF410E0B)
val day_md_theme_light_background = Color(0xFFFFFFFF)
val day_md_theme_light_onBackground = Color(0xFF1b1b1b)
val day_md_theme_light_surface = Color(0xFFFDFCFF)
val day_md_theme_light_onSurface = Color(0xFF1B1B1B)
val day_md_theme_light_surfaceVariant = Color(0xFFE7E0EC)
val day_md_theme_light_onSurfaceVariant = Color(0xFF49454F)
val day_md_theme_light_outline = Color(0x10000000)
val day_md_theme_light_inverseOnSurface = Color(0xFFF1F0F4)
val day_md_theme_light_inverseSurface = Color(0xFF2F3033)
val day_md_theme_light_inversePrimary = Color(0xFF59D5F8)
val day_md_theme_light_shadow = Color(0xFF000000)

val day_seed = Color(0xFF6750A4)
val day_error = Color(0xFFB3261E)