package wangdaye.com.geometricweather.background.receiver.widget.androidSWeather

import wangdaye.com.geometricweather.background.receiver.widget.AbstractWidgetProvider

class WidgetAndroidSWeatherLargeProvider: AbstractWidgetProvider()